name: XRayHunter
main: dk.lockfuglsang.xrayhunter.XRayHunter
version: ${project.version}
description: XRay Hunter for CoreProtect v${project.version}-${buildNumber}-${travis.buildNumber}
author: R4zorax
softdepend: [CoreProtect]
api-version: 1.13
commands:
    xrayhunt:
        description: Hunt XRayers
        aliases: [xhunt, xr]
        usage: |
          /<command> - Access XRay Hunter

permissions:    
  xhunt.*:
    children:
      xhunt.use:
        description: Let the player use the /xhunt command